import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import './globals.css'
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "This is my app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link
          href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
      
      >
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
              {children}
          </ThemeProvider>
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}
